name: Genesis OS Full Auto Build & Assemble

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read
      checks: write

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/*.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set ANDROID_SDK_ROOT environment variable
      run: echo "ANDROID_SDK_ROOT=${{ runner.temp }}/android-sdk" >> $GITHUB_ENV

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant Execute Permission to Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Assemble Debug APK
      run: ./gradlew assembleDebug

    - name: Upload Build Artifacts (APK/JAR/AAR)
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          app/build/outputs/apk/debug/*.apk
          **/build/libs/*.jar
          **/build/outputs/**/*.aar
