package dev.aurakai.auraframefx.ai.agents

import dev.aurakai.auraframefx.model.AgentResponse
import dev.aurakai.auraframefx.model.AgentType
import dev.aurakai.auraframefx.model.AiRequest
import kotlinx.coroutines.flow.Flow

/**
 * Top-level value declaration for versioning or identification.
 */
const val TOPL_VL: String = "1.0.0"

/**
 * Interface representing an AI agent.
 */
interface Agent {
    /**
 * Returns the name of the agent, or null if the name is not set.
 *
 * @return The agent's name, or null if unavailable.
 */
    fun getName(): String?

    /**
 * Returns the classification type of the agent.
 *
 * @return The agent's type.
 */
    fun getType(): AgentType

    /**
 * Processes an AI request using the provided context and returns the resulting agent response.
 *
 * @param request The AI request to be handled.
 * @param context Contextual information to guide the agent's processing of the request.
 * @return The response generated by the agent for the given request and context.
 */
    suspend fun processRequest(request: AiRequest, context: String): AgentResponse

    /**
 * Processes an AI request and returns a flow of agent responses.
 *
 * Allows the agent to emit multiple or streaming responses for a single request.
 *
 * @param request The AI request to process.
 * @return A flow emitting one or more agent responses.
 */
    fun processRequestFlow(request: AiRequest): Flow<AgentResponse>
}