package dev.aurakai.auraframefx.ai.agents

import dev.aurakai.auraframefx.model.AgentResponse
import dev.aurakai.auraframefx.model.AgentType
import dev.aurakai.auraframefx.model.AiRequest
import kotlinx.coroutines.flow.Flow

/**
 * Top-level value declaration for versioning or identification.
 */
const val TOPL_VL: String = "1.0.0"

/**
 * Interface representing an AI agent.
 */
interface Agent {
    /**
 * Retrieves the name of the agent.
 *
 * @return The agent's name, or null if not set.
 */
    fun getName(): String?

    /**
 * Retrieves the type or classification of the agent.
 *
 * @return The agent's type as an `AgentType`.
 */
    fun getType(): AgentType

    /**
 * Processes an AI request with the given context and returns the agent's response.
 *
 * @param request The AI request to process.
 * @param context Additional context information for the request.
 * @return The response generated by the agent.
 */
    suspend fun processRequest(request: AiRequest, context: String): AgentResponse

    /**
 * Processes an AI request and returns a flow of agent responses.
 *
 * Enables streaming or multiple responses for a single request.
 *
 * @param request The AI request to process.
 * @return A flow emitting one or more agent responses.
 */
    fun processRequestFlow(request: AiRequest): Flow<AgentResponse>
}